export const QUEST_INFO_REQUEST = 'QUEST_INFO_REQUEST';
export const QUEST_INFO_SUCCESS = 'QUEST_INFO_SUCCESS';
export const QUEST_INFO_ERROR = 'QUEST_INFO_ERROR';

// TASKS

export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_ERROR = 'TASKS_ERROR';
