export const QUEST_INFO_REQUEST = 'QUEST_INFO_REQUEST';
export const QUEST_INFO_SUCCESS = 'QUEST_INFO_SUCCESS';
export const QUEST_INFO_ERROR = 'QUEST_INFO_ERROR';

export const QUEST_DELETE_REQUEST = 'QUEST_DELETE_REQUEST';
export const QUEST_DELETE_SUCCESS = 'QUEST_DELETE_SUCCESS';
export const QUEST_DELETE_ERROR = 'QUEST_DELETE_ERROR';

export const REQUEST_QUESTS_BY_AUTHOR = 'REQUEST_QUESTS_BY_AUTHOR';
export const SUCCESS_QUESTS_BY_AUTHOR = 'SUCCESS_QUESTS_BY_AUTHOR';
export const ERROR_QUESTS_BY_AUTHOR = 'ERROR_QUESTS_BY_AUTHOR';

export const QUESTS_IN_PROGRESS_REQUEST = 'QUESTS_IN_PROGRESS_REQUEST';
export const QUESTS_IN_PROGRESS_SUCCESS = 'QUESTS_IN_PROGRESS_SUCCESS';
export const QUESTS_IN_PROGRESS_ERROR = 'QUESTS_IN_PROGRESS_ERROR';

// TASKS

export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_ERROR = 'TASKS_ERROR';
export const TASK_COORDINATES_CORRECT = 'TASK_COORDINATES_CORRECT';
export const TASK_COORDINATES_INCORRECT = 'TASK_COORDINATES_INCORRECT';
