export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
